<template>
  <div class="software-development_content">
    <div class="software-development_content__content-item_wrapper">
      <h3 class="software-development_content__title title" v-if="title === 'Mobile'">
        <span>Mobi</span>
        <img
          class="software-development_content__mobile-title-icon title-icon"
          src="../../assets/img/Services/svg/phone-title-symbol.svg"
          alt="phone-title-symbol"
        />
        <span class="software-development_content__last-character last-character">e</span>
      </h3>
      <h3 class="software-development_content__title title" v-else>{{ title }}</h3>
      <h4 class="software-development_content__sub-title sub-title">{{ subTitle }}</h4>
      <p class="software-development_content__paragraph paragraph">{{ firstParagraph }}</p>
      <p class="software-development_content__paragraph paragraph">{{ secondParagraph }}</p>
      <p class="software-development_content__paragraph paragraph" v-if="title === 'Backend'">{{ thirdParagraph }}</p>
        <div class="software-development_content__icon-flex-group">
          <TechIcon v-for="(icon, i) in icons" :key="i" :class-prefix="icon.prefix" :title="icon.title"/>
        </div>
    </div>
  </div>
</template>

<script>
import TechnologiesItem from '@/components/About/TechnologiesItem';
import TechIcon from '@/components/IconsGroup/tech-icon';

export default {
  name: 'SoftwareDevelopmentContent',
  props: {
    title: {
      type: String,
      default: 'Title'
    },
    subTitle: {
      type: String,
      default: 'Sub Title'
    },
    firstParagraph: {
      type: String,
      default: 'First Paragraph'
    },
    secondParagraph: {
      type: String,
      default: 'Second Paragraph'
    },
    thirdParagraph: {
      type: String,
      default: 'Third Paragraph'
    },
    icons: {
      type: Array,
      default: () => []
    }
  },
  components: {
    TechnologiesItem,
    TechIcon
  },

  data() {
    return {
      technologies: [
        {
          title: 'Frontend',
          class: 'technologies-frontend',
          paragraph: 'We do frontend development at a fast pace, in accordance with ES6 standards. To create easy-to-maintain projects, we use current tools & technologies:'
        },
        {
          title: 'Mobile',
          class: 'technologies-mobile',
          paragraph: 'We don\'t just create mobile apps, we make them intuitive for super-smooth user journeys. Mad Devs do both iOs and Android development and perform audits of existing applications. You can turn to our mobile developers for any of the following programming languages:'
        },
        {
          title: 'Backend',
          class: 'technologies-backend',
          paragraph: 'We build reliable backends for the heavy workloads generated by millions of users. Our team has experience with nearly all the popular programming languages:'
        }
      ]
    };
  }
};
</script>

<style lang="scss" scoped>
   @import '../../assets/styles/vars';
   @import '../../assets/styles/get-vw';

   .software-development_content {
    max-width: get-vw(440px);
    min-width: calc(1em + 4vw);
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    padding-top: get-vw(143px);

    &:last-child {
      padding-right: 0;
    }

    &__content-item_wrapper {
      color: $text-color--grey;
    }

    &__sub-title {
      padding-bottom: get-vw(12px);
      line-height: 110%;
      letter-spacing: get-vw(-1px);
    }

    &__paragraph {
      max-width: get-vw(360px);
      line-height: 139%;
    }

    &__mobile-title-icon {
      margin-left: get-vw(-24px);
      margin-bottom: get-vw(-10px);
      padding-right: 1vw;
    }

    /deep/.icon-item {
      padding-bottom: get-vw(15px);
      padding-right: get-vw(40px);
    }

    /deep/.icons-list {
      padding-top: get-vw(18px);
      padding-bottom: get-vw(46px);
    }

    &__title {
      line-height: 110%;
      letter-spacing: get-vw(-3px);
      white-space: nowrap;
    }

    &__icon-flex-group {
      display: flex;
      flex-wrap: wrap;
      margin-top: get-vw(17px);
    }
  }

  @media only screen and (max-width: 1280px) {
    .software-development_content {

      &__main-title {
        padding-bottom: 52px;
      }

      &__sub-title {
        letter-spacing: -1px;
      }
    }
  }

  @media only screen and (max-width: 1024px) {
    .software-development_content {
      max-width: initial;
      padding-right: 0;

      &__title,
      &__paragraph {
        max-width: initial;
      }

      &__mobile-title-icon {
        margin-left: -1.5vw;
        margin-bottom: -0.23vw;
        padding-right: 2vw;
      }
    }
  }

   @media only screen and (max-width: 780px) {
     .software-development_content {
       &__mobile-title-icon {
         padding-right: 3vw;
         margin-left: -1.5vw;
       }
     }
   }

   @media only screen and (max-width: 640px) {
     .software-development_content {
       &__mobile-title-icon {
         padding-right: 1vw;
         margin-bottom: 0;
         margin-left: -3vw;
       }
     }
   }

  @media only screen and (max-width: 695px) {
    .software-development_content {
      /deep/.icons-list {
        flex-wrap: wrap;
      }

      /deep/.icon-flex_group {
        display: block;

        &:last-child {
          flex-direction: column;
        }
      }

      &:nth-child(2),
      &:nth-child(3) {
        /deep/.icon-flex_group {
          display: block;

          &:first-child {
            /deep/.icon-item {
              padding-right: 70px;
            }
          }

          &:last-child {
            flex-direction: column;
          }
        }
      }

      &__sub-title {
        font-size: 7vw;
        padding-bottom: 3vw;
      }

      &__title {
        padding: 4vw 0;
      }

      &__paragraph {
        padding-bottom: 12px;
      }
    }
  }

  @media only screen and (max-width: 458px) {
    .software-development_content {
      &__mobile-title-icon {
        padding-right: 3.5vw;
        margin-bottom: -0.5vw;
        margin-left: -2.5vw;
      }

      &:first-child {
        /deep/.icon-flex_group {
        display: flex;
        flex-direction: column;

          &:last-child {
            flex-direction: row;

            /deep/.icon-item:first-child {
              padding-right: 70px;
            }
          }

          &:first-child {
            /deep/.icon-item {
              padding-right: 70px;
            }
          }
        }
      }

      /deep/.icon-flex_group {
        display: flex;
        flex-direction: column;

        &:first-child {
          /deep/.icon-item {
            padding-right: 70px;
          }
        }
      }
    }
  }
</style>
