const dotenv = require('dotenv')

dotenv.config()

// Atlassian
const ATLASSIAN_TOKEN = process.env.NODE_ATLASSIAN_TOKEN
const ATLASSIAN_EMAIL = process.env.NODE_ATLASSIAN_EMAIL
const ATLASSIAN_AUTH_TOKEN = `${ATLASSIAN_EMAIL}:${ATLASSIAN_TOKEN}`
const ATLASSIAN_PROJECT_KEY = process.env.NODE_ATLASSIAN_PROJECT_KEY
const ATLASSIAN_API_URL = process.env.NODE_ATLASSIAN_API_URL

// Send pulse
const SENDPULSE_API_KEY = process.env.NODE_SENDPULSE_API_KEY
const SENDPULSE_API_USER_ID = process.env.NODE_SENDPULSE_API_USER_ID
const SENDPULSE_TOKEN_STORAGE = '/tmp/'

// Huntflow
const HUNTFLOW_TOKEN = process.env.NODE_HUNTFLOW_TOKEN
const HUNTFLOW_API_URL = process.env.NODE_HUNTFLOW_API_URL
const HUNTFLOW_ACCOUNT_ID = process.env.NODE_HUNTFLOW_ACCOUNT_ID

// Sentry
const SENTRY_DSN = process.env.NODE_SENTRY_DSN

// Other
const { NODE_ENV } = process.env

module.exports = {
  ATLASSIAN_TOKEN,
  ATLASSIAN_EMAIL,
  ATLASSIAN_AUTH_TOKEN,
  ATLASSIAN_PROJECT_KEY,
  ATLASSIAN_API_URL,
  SENDPULSE_API_USER_ID,
  SENDPULSE_API_KEY,
  SENDPULSE_TOKEN_STORAGE,
  HUNTFLOW_TOKEN,
  HUNTFLOW_API_URL,
  HUNTFLOW_ACCOUNT_ID,
  SENTRY_DSN,
  NODE_ENV,
}
