<template>
  <section id="technologies-and-tools" class="technologies-and_tools">
    <div class="container">
      <div class="technologies-and_tools__content-wrap">
        <h2 class="technologies-and_tools__main-title main-title">
            Technologies <br> & Tools
        </h2>
        <div class="technologies-and_tools__technologies-list">
          <div class="technologies-and_tools__flex-group">
            <TechnologiesItem
              :title="frontend.title"
              :paragraph="frontend.paragraph"
              class="technologies-frontend"
            />
            <TechnologiesItem
              :title="backend.title"
              :paragraph="backend.paragraph"
              class="technologies-backend"
            />
          </div>
          <div class="technologies-and_tools__flex-group">
            <div class="technologies-and_tools__sub-flex_group">
              <TechnologiesItem
                :title="mobile.title"
                :paragraph="mobile.paragraph"
                class="technologies-mobile"
              />
              <TechnologiesItem
                :title="projectManagement.title"
                :paragraph="projectManagement.paragraph"
              />
            </div>
            <InfrastructureTechnologiesItem />
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
import TechnologiesItem from '@/components/About/TechnologiesItem';
import InfrastructureTechnologiesItem from '@/components/About/InfrastructureTechnologiesItem';

export default {
  name: 'TechnologiesAndTools',
  components: {
    TechnologiesItem,
    InfrastructureTechnologiesItem
  },
  data() {
    return {
      frontend: {
        title: 'Frontend',
        paragraph: 'We do frontend development at a fast pace, in accordance with ES6 standards. To create easy-to-maintain projects, we use current tools & technologies:'
      },
      mobile: {
        title: 'Mobile',
        paragraph: 'We don\'t just create mobile apps, we make them intuitive for super-smooth user journeys. Mad Devs do both iOs and Android development and perform audits of existing applications. You can turn to our mobile developers for any of the following programming languages:'
      },
      backend: {
        title: 'Backend',
        paragraph: 'We build reliable backends for the heavy workloads generated by millions of users. Our team has experience with nearly all the popular programming languages:'
      },
      projectManagement: {
        title: 'Project Management',
        paragraph: 'Our project managers can provide you with a detailed report on the workload of every team member. We use modern tools and solutions for task tracking, team sync-ups and our daily communication process:'
      }
    };
  }
};
</script>

<style lang="scss" scoped>
  @import '../../assets/styles/vars';

  .technologies-and_tools {
    padding-bottom: 183px;

    &__main-title {
      padding-bottom: 41px;
      color: $text-color--white;
    }

    &__technologies-list {
      display: flex;
      flex-direction: column;
      justify-content: space-between;
    }

    &__flex-group {
      display: flex;
      justify-content: space-between;

      div {
        max-width: 650px;
      }
    }
  }

  @media only screen and (max-width: 1420px) {
    .technologies-and_tools {
      &__flex-group {
        div {
          max-width: 520px;
        }
      }
    }
  }

  @media only screen and (max-width: 1180px) {
    .technologies-and_tools {
      &__flex-group {
        div {
          max-width: 435px;
        }
      }
    }
  }

  @media only screen and (max-width: 1024px) {
    .technologies-and_tools {
      &__flex-group {
        flex-direction: column;

        div {
          max-width: initial;
        }

        &:first-child {
          flex-direction: column-reverse;
        }
      }
    }
  }

  @media only screen and (max-width: 520px) {
    .technologies-and_tools {
      padding-bottom: 75px;
      &__main-title {
        padding-bottom: 31px;
      }
    }
  }
</style>
