<template>
  <section id="technologies-and-tools" class="TechnologiesAndTools">
    <div class="container">
      <div class="technologiesAndTools__content-wrap">
        <h2 class="we-create-it-project__main-title main-title">
            Technologies <br> & Tools
        </h2>
        <div class="technologiesAndTools__technologies-list">
          <TechnologiesItem
            :title="frontend.title"
            :paragraph="frontend.paragraph" 
          />
          <TechnologiesItem
            :title="mobile.title"
            :paragraph="mobile.paragraph" 
          />
          <TechnologiesItem
            :title="backend.title"
            :paragraph="backend.paragraph" 
          />
          <TechnologiesItem
            :title="projectManagement.title"
            :paragraph="projectManagement.paragraph" 
          />
          <TechnologiesItem
            :title="infrastructure.title"
            :firstParagraph="infrastructure.firstParagraph" 
            :secondParagraph="infrastructure.secondParagraph"
          />
        </div>
      </div>
    </div>
  </section>
</template>

<script>
import TechnologiesItem from '@/components/About/TechnologiesItem';

export default {
  name: 'TechnologiesAndTools',
  components: {
    TechnologiesItem
  },
  data() {
    return {
      frontend: {
        title: 'Frontend',
        paragraph: 'We do frontend development at a fast pace, in accordance with ES6 standards. To create easy-to-maintain projects, we use current tools & technologies:'
      },
      mobile: {
        title: 'Mobile',
        paragraph: 'We don\'t just create mobile apps, we make them intuitive for super-smooth user journeys. Mad Devs do both iOs and Android development and perform audits of existing applications. You can turn to our mobile developers for any of the following programming languages:'
      },
      backend: {
        title: 'Backend',
        paragraph: 'We build reliable backends for the heavy workloads generated by millions of users. Our team has experience with nearly all the popular programming languages:'
      },
      projectManagement: {
        title: 'Project Management',
        paragraph: 'Our project managers can provide you with a detailed report on the workload of every team member. We use modern tools and solutions for task tracking, team sync-ups and our daily communication process:'
      },
      infrastructure: {
        title: 'Infrastructure',
        firstParagraph: 'We have helped our customers save up to 50% on infrastructure by optimising their cloud-resource consumption. We know how to get the best value for money, whichever cloud service provider you choose:',
        secondParagraph: 'Mad Devs infrastructure leads also have expertise with a with a wide range of tools for tools сonfiguration, СI/CD and monitoring:'
      }
    };
  }
};
</script>

<style lang="scss" scoped>
  @import '../../assets/styles/vars';
</style>
